
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
* This file exports all enum related types from the schema.
*
* 🟢 You can import this file directly.
*/

export const OrderStatus = {
  DRAFT: 'DRAFT',
  PROFORMA_SENT: 'PROFORMA_SENT',
  ADVANCE_RECEIVED: 'ADVANCE_RECEIVED',
  IN_PRODUCTION: 'IN_PRODUCTION',
  READY_FOR_DISPATCH: 'READY_FOR_DISPATCH',
  SHIPPED: 'SHIPPED',
  PAYMENT_REALIZED: 'PAYMENT_REALIZED',
  REGULATORY_CLOSED: 'REGULATORY_CLOSED'
} as const

export type OrderStatus = (typeof OrderStatus)[keyof typeof OrderStatus]


export const Incoterm = {
  EXW: 'EXW',
  FOB: 'FOB',
  CIF: 'CIF',
  DAP: 'DAP'
} as const

export type Incoterm = (typeof Incoterm)[keyof typeof Incoterm]


export const PaymentType = {
  ADVANCE: 'ADVANCE',
  BALANCE: 'BALANCE'
} as const

export type PaymentType = (typeof PaymentType)[keyof typeof PaymentType]


export const FileType = {
  SWIFT_COPY: 'SWIFT_COPY',
  SHIPPING_BILL: 'SHIPPING_BILL',
  BL_COPY: 'BL_COPY',
  CUSTOM_DESIGN: 'CUSTOM_DESIGN',
  OTHER: 'OTHER'
} as const

export type FileType = (typeof FileType)[keyof typeof FileType]
