
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the browser.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from "@prisma/client/runtime/index-browser"

export type * from '../models'
export type * from './prismaNamespace'

export const Decimal = runtime.Decimal


export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as (new (secret: never) => typeof runtime.DbNull),
  JsonNull: runtime.NullTypes.JsonNull as (new (secret: never) => typeof runtime.JsonNull),
  AnyNull: runtime.NullTypes.AnyNull as (new (secret: never) => typeof runtime.AnyNull),
}
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull


export const ModelName = {
  CompanyProfile: 'CompanyProfile',
  Buyer: 'Buyer',
  Product: 'Product',
  ProductVariant: 'ProductVariant',
  Order: 'Order',
  OrderItem: 'OrderItem',
  PaymentLedger: 'PaymentLedger',
  DocumentAttachment: 'DocumentAttachment'
} as const

export type ModelName = (typeof ModelName)[keyof typeof ModelName]

/*
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable'
} as const)

export type TransactionIsolationLevel = (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel]


export const CompanyProfileScalarFieldEnum = {
  id: 'id',
  companyName: 'companyName',
  iecCode: 'iecCode',
  adCode: 'adCode',
  gstin: 'gstin',
  lutNumber: 'lutNumber',
  lutExpiryDate: 'lutExpiryDate',
  updatedAt: 'updatedAt'
} as const

export type CompanyProfileScalarFieldEnum = (typeof CompanyProfileScalarFieldEnum)[keyof typeof CompanyProfileScalarFieldEnum]


export const BuyerScalarFieldEnum = {
  id: 'id',
  companyName: 'companyName',
  contactPerson: 'contactPerson',
  billingAddress: 'billingAddress',
  shippingAddress: 'shippingAddress',
  country: 'country',
  taxId: 'taxId',
  preferredCurrency: 'preferredCurrency',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type BuyerScalarFieldEnum = (typeof BuyerScalarFieldEnum)[keyof typeof BuyerScalarFieldEnum]


export const ProductScalarFieldEnum = {
  id: 'id',
  skuBase: 'skuBase',
  description: 'description',
  hsCode: 'hsCode',
  unitPriceUsd: 'unitPriceUsd',
  moq: 'moq',
  weightNet: 'weightNet',
  weightGross: 'weightGross',
  cbm: 'cbm',
  createdAt: 'createdAt'
} as const

export type ProductScalarFieldEnum = (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum]


export const ProductVariantScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  skuFull: 'skuFull',
  color: 'color',
  leatherType: 'leatherType',
  stockAllocation: 'stockAllocation'
} as const

export type ProductVariantScalarFieldEnum = (typeof ProductVariantScalarFieldEnum)[keyof typeof ProductVariantScalarFieldEnum]


export const OrderScalarFieldEnum = {
  id: 'id',
  documentNumber: 'documentNumber',
  status: 'status',
  buyerId: 'buyerId',
  incoterm: 'incoterm',
  portOfLoading: 'portOfLoading',
  portOfDischarge: 'portOfDischarge',
  vesselName: 'vesselName',
  awbBlNumber: 'awbBlNumber',
  shippingBillNumber: 'shippingBillNumber',
  shippingBillDate: 'shippingBillDate',
  currency: 'currency',
  subTotal: 'subTotal',
  freightCost: 'freightCost',
  insuranceCost: 'insuranceCost',
  grandTotal: 'grandTotal',
  lockedExchangeRate: 'lockedExchangeRate',
  appliedLutNumber: 'appliedLutNumber',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt'
} as const

export type OrderScalarFieldEnum = (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum]


export const OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  variantId: 'variantId',
  quantity: 'quantity',
  historicalUnitPrice: 'historicalUnitPrice',
  historicalDescription: 'historicalDescription',
  historicalHsCode: 'historicalHsCode',
  historicalNetWeight: 'historicalNetWeight',
  historicalGrossWeight: 'historicalGrossWeight',
  historicalCbm: 'historicalCbm',
  lineTotal: 'lineTotal'
} as const

export type OrderItemScalarFieldEnum = (typeof OrderItemScalarFieldEnum)[keyof typeof OrderItemScalarFieldEnum]


export const PaymentLedgerScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  amount: 'amount',
  currency: 'currency',
  exchangeRate: 'exchangeRate',
  paymentType: 'paymentType',
  paymentDate: 'paymentDate',
  referenceId: 'referenceId',
  eBrcNumber: 'eBrcNumber',
  eBrcDate: 'eBrcDate',
  bankFircNumber: 'bankFircNumber'
} as const

export type PaymentLedgerScalarFieldEnum = (typeof PaymentLedgerScalarFieldEnum)[keyof typeof PaymentLedgerScalarFieldEnum]


export const DocumentAttachmentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  fileName: 'fileName',
  s3ObjectKey: 's3ObjectKey',
  fileType: 'fileType',
  createdAt: 'createdAt'
} as const

export type DocumentAttachmentScalarFieldEnum = (typeof DocumentAttachmentScalarFieldEnum)[keyof typeof DocumentAttachmentScalarFieldEnum]


export const SortOrder = {
  asc: 'asc',
  desc: 'desc'
} as const

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder]


export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive'
} as const

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode]


export const NullsOrder = {
  first: 'first',
  last: 'last'
} as const

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder]

