/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck
/*
 * WARNING: This is an internal file that is subject to change!
 *
 * 🛑 Under no circumstances should you import this file directly! 🛑
 *
 * All exports from this file are wrapped under a `Prisma` namespace object in the client.ts file.
 * While this enables partial backward compatibility, it is not part of the stable public API.
 *
 * If you are looking for your Models, Enums, and Input Types, please import them from the respective
 * model files in the `model` directory!
 */

import * as runtime from '@prisma/client/runtime/client';
import type * as Prisma from '../models';
import { type PrismaClient } from './class';

export type * from '../models';

export type DMMF = typeof runtime.DMMF;

export type PrismaPromise<T> = runtime.Types.Public.PrismaPromise<T>;

/**
 * Prisma Errors
 */

export const PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError;
export type PrismaClientKnownRequestError = runtime.PrismaClientKnownRequestError;

export const PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError;
export type PrismaClientUnknownRequestError = runtime.PrismaClientUnknownRequestError;

export const PrismaClientRustPanicError = runtime.PrismaClientRustPanicError;
export type PrismaClientRustPanicError = runtime.PrismaClientRustPanicError;

export const PrismaClientInitializationError = runtime.PrismaClientInitializationError;
export type PrismaClientInitializationError = runtime.PrismaClientInitializationError;

export const PrismaClientValidationError = runtime.PrismaClientValidationError;
export type PrismaClientValidationError = runtime.PrismaClientValidationError;

/**
 * Re-export of sql-template-tag
 */
export const sql = runtime.sqltag;
export const empty = runtime.empty;
export const join = runtime.join;
export const raw = runtime.raw;
export const Sql = runtime.Sql;
export type Sql = runtime.Sql;

/**
 * Decimal.js
 */
export const Decimal = runtime.Decimal;
export type Decimal = runtime.Decimal;

export type DecimalJsLike = runtime.DecimalJsLike;

/**
 * Extensions
 */
export type Extension = runtime.Types.Extensions.UserArgs;
export const getExtensionContext = runtime.Extensions.getExtensionContext;
export type Args<T, F extends runtime.Operation> = runtime.Types.Public.Args<T, F>;
export type Payload<T, F extends runtime.Operation = never> = runtime.Types.Public.Payload<T, F>;
export type Result<T, A, F extends runtime.Operation> = runtime.Types.Public.Result<T, A, F>;
export type Exact<A, W> = runtime.Types.Public.Exact<A, W>;

export type PrismaVersion = {
  client: string;
  engine: string;
};

/**
 * Prisma Client JS version: 7.7.0
 * Query Engine version: 75cbdc1eb7150937890ad5465d861175c6624711
 */
export const prismaVersion: PrismaVersion = {
  client: '7.7.0',
  engine: '75cbdc1eb7150937890ad5465d861175c6624711',
};

/**
 * Utility Types
 */

export type Bytes = runtime.Bytes;
export type JsonObject = runtime.JsonObject;
export type JsonArray = runtime.JsonArray;
export type JsonValue = runtime.JsonValue;
export type InputJsonObject = runtime.InputJsonObject;
export type InputJsonArray = runtime.InputJsonArray;
export type InputJsonValue = runtime.InputJsonValue;

export const NullTypes = {
  DbNull: runtime.NullTypes.DbNull as new (secret: never) => typeof runtime.DbNull,
  JsonNull: runtime.NullTypes.JsonNull as new (secret: never) => typeof runtime.JsonNull,
  AnyNull: runtime.NullTypes.AnyNull as new (secret: never) => typeof runtime.AnyNull,
};
/**
 * Helper for filtering JSON entries that have `null` on the database (empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const DbNull = runtime.DbNull;

/**
 * Helper for filtering JSON entries that have JSON `null` values (not empty on the db)
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const JsonNull = runtime.JsonNull;

/**
 * Helper for filtering JSON entries that are `Prisma.DbNull` or `Prisma.JsonNull`
 *
 * @see https://www.prisma.io/docs/concepts/components/prisma-client/working-with-fields/working-with-json-fields#filtering-on-a-json-field
 */
export const AnyNull = runtime.AnyNull;

type SelectAndInclude = {
  select: any;
  include: any;
};

type SelectAndOmit = {
  select: any;
  omit: any;
};

/**
 * From T, pick a set of properties whose keys are in the union K
 */
type Prisma__Pick<T, K extends keyof T> = {
  [P in K]: T[P];
};

export type Enumerable<T> = T | Array<T>;

/**
 * Subset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection
 */
export type Subset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
};

/**
 * SelectSubset
 * @desc From `T` pick properties that exist in `U`. Simple version of Intersection.
 * Additionally, it validates, if both select and include are present. If the case, it errors.
 */
export type SelectSubset<T, U> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
} & (T extends SelectAndInclude
  ? 'Please either choose `select` or `include`.'
  : T extends SelectAndOmit
    ? 'Please either choose `select` or `omit`.'
    : {});

/**
 * Subset + Intersection
 * @desc From `T` pick properties that exist in `U` and intersect `K`
 */
export type SubsetIntersection<T, U, K> = {
  [key in keyof T]: key extends keyof U ? T[key] : never;
} & K;

type Without<T, U> = { [P in Exclude<keyof T, keyof U>]?: never };

/**
 * XOR is needed to have a real mutually exclusive union type
 * https://stackoverflow.com/questions/42123407/does-typescript-support-mutually-exclusive-types
 */
export type XOR<T, U> = T extends object
  ? U extends object
    ? (Without<T, U> & U) | (Without<U, T> & T)
    : U
  : T;

/**
 * Is T a Record?
 */
type IsObject<T extends any> =
  T extends Array<any>
    ? False
    : T extends Date
      ? False
      : T extends Uint8Array
        ? False
        : T extends BigInt
          ? False
          : T extends object
            ? True
            : False;

/**
 * If it's T[], return T
 */
export type UnEnumerate<T extends unknown> = T extends Array<infer U> ? U : T;

/**
 * From ts-toolbelt
 */

type __Either<O extends object, K extends Key> = Omit<O, K> &
  {
    // Merge all but K
    [P in K]: Prisma__Pick<O, P & keyof O>; // With K possibilities
  }[K];

type EitherStrict<O extends object, K extends Key> = Strict<__Either<O, K>>;

type EitherLoose<O extends object, K extends Key> = ComputeRaw<__Either<O, K>>;

type _Either<O extends object, K extends Key, strict extends Boolean> = {
  1: EitherStrict<O, K>;
  0: EitherLoose<O, K>;
}[strict];

export type Either<O extends object, K extends Key, strict extends Boolean = 1> = O extends unknown
  ? _Either<O, K, strict>
  : never;

export type Union = any;

export type PatchUndefined<O extends object, O1 extends object> = {
  [K in keyof O]: O[K] extends undefined ? At<O1, K> : O[K];
} & {};

/** Helper Types for "Merge" **/
export type IntersectOf<U extends Union> = (U extends unknown ? (k: U) => void : never) extends (
  k: infer I
) => void
  ? I
  : never;

export type Overwrite<O extends object, O1 extends object> = {
  [K in keyof O]: K extends keyof O1 ? O1[K] : O[K];
} & {};

type _Merge<U extends object> = IntersectOf<
  Overwrite<
    U,
    {
      [K in keyof U]-?: At<U, K>;
    }
  >
>;

type Key = string | number | symbol;
type AtStrict<O extends object, K extends Key> = O[K & keyof O];
type AtLoose<O extends object, K extends Key> = O extends unknown ? AtStrict<O, K> : never;
export type At<O extends object, K extends Key, strict extends Boolean = 1> = {
  1: AtStrict<O, K>;
  0: AtLoose<O, K>;
}[strict];

export type ComputeRaw<A extends any> = A extends Function
  ? A
  : {
      [K in keyof A]: A[K];
    } & {};

export type OptionalFlat<O> = {
  [K in keyof O]?: O[K];
} & {};

type _Record<K extends keyof any, T> = {
  [P in K]: T;
};

// cause typescript not to expand types and preserve names
type NoExpand<T> = T extends unknown ? T : never;

// this type assumes the passed object is entirely optional
export type AtLeast<O extends object, K extends string> = NoExpand<
  O extends unknown
    ?
        | (K extends keyof O ? { [P in K]: O[P] } & O : O)
        | ({ [P in keyof O as P extends K ? P : never]-?: O[P] } & O)
    : never
>;

type _Strict<U, _U = U> = U extends unknown
  ? U & OptionalFlat<_Record<Exclude<Keys<_U>, keyof U>, never>>
  : never;

export type Strict<U extends object> = ComputeRaw<_Strict<U>>;
/** End Helper Types for "Merge" **/

export type Merge<U extends object> = ComputeRaw<_Merge<Strict<U>>>;

export type Boolean = True | False;

export type True = 1;

export type False = 0;

export type Not<B extends Boolean> = {
  0: 1;
  1: 0;
}[B];

export type Extends<A1 extends any, A2 extends any> = [A1] extends [never]
  ? 0 // anything `never` is false
  : A1 extends A2
    ? 1
    : 0;

export type Has<U extends Union, U1 extends Union> = Not<Extends<Exclude<U1, U>, U1>>;

export type Or<B1 extends Boolean, B2 extends Boolean> = {
  0: {
    0: 0;
    1: 1;
  };
  1: {
    0: 1;
    1: 1;
  };
}[B1][B2];

export type Keys<U extends Union> = U extends unknown ? keyof U : never;

export type GetScalarType<T, O> = O extends object
  ? {
      [P in keyof T]: P extends keyof O ? O[P] : never;
    }
  : never;

type FieldPaths<T, U = Omit<T, '_avg' | '_sum' | '_count' | '_min' | '_max'>> =
  IsObject<T> extends True ? U : T;

export type GetHavingFields<T> = {
  [K in keyof T]: Or<Or<Extends<'OR', K>, Extends<'AND', K>>, Extends<'NOT', K>> extends True
    ? // infer is only needed to not hit TS limit
      // based on the brilliant idea of Pierre-Antoine Mills
      // https://github.com/microsoft/TypeScript/issues/30188#issuecomment-478938437
      T[K] extends infer TK
      ? GetHavingFields<UnEnumerate<TK> extends object ? Merge<UnEnumerate<TK>> : never>
      : never
    : {} extends FieldPaths<T[K]>
      ? never
      : K;
}[keyof T];

/**
 * Convert tuple to union
 */
type _TupleToUnion<T> = T extends (infer E)[] ? E : never;
type TupleToUnion<K extends readonly any[]> = _TupleToUnion<K>;
export type MaybeTupleToUnion<T> = T extends any[] ? TupleToUnion<T> : T;

/**
 * Like `Pick`, but additionally can also accept an array of keys
 */
export type PickEnumerable<T, K extends Enumerable<keyof T> | keyof T> = Prisma__Pick<
  T,
  MaybeTupleToUnion<K>
>;

/**
 * Exclude all keys with underscores
 */
export type ExcludeUnderscoreKeys<T extends string> = T extends `_${string}` ? never : T;

export type FieldRef<Model, FieldType> = runtime.FieldRef<Model, FieldType>;

type FieldRefInputType<Model, FieldType> = Model extends never ? never : FieldRef<Model, FieldType>;

export const ModelName = {
  CompanyProfile: 'CompanyProfile',
  Buyer: 'Buyer',
  Product: 'Product',
  ProductVariant: 'ProductVariant',
  Order: 'Order',
  OrderItem: 'OrderItem',
  PaymentLedger: 'PaymentLedger',
  DocumentAttachment: 'DocumentAttachment',
} as const;

export type ModelName = (typeof ModelName)[keyof typeof ModelName];

export interface TypeMapCb<GlobalOmitOptions = {}> extends runtime.Types.Utils.Fn<
  { extArgs: runtime.Types.Extensions.InternalArgs },
  runtime.Types.Utils.Record<string, any>
> {
  returns: TypeMap<this['params']['extArgs'], GlobalOmitOptions>;
}

export type TypeMap<
  ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs,
  GlobalOmitOptions = {},
> = {
  globalOmitOptions: {
    omit: GlobalOmitOptions;
  };
  meta: {
    modelProps:
      | 'companyProfile'
      | 'buyer'
      | 'product'
      | 'productVariant'
      | 'order'
      | 'orderItem'
      | 'paymentLedger'
      | 'documentAttachment';
    txIsolationLevel: TransactionIsolationLevel;
  };
  model: {
    CompanyProfile: {
      payload: Prisma.$CompanyProfilePayload<ExtArgs>;
      fields: Prisma.CompanyProfileFieldRefs;
      operations: {
        findUnique: {
          args: Prisma.CompanyProfileFindUniqueArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyProfilePayload> | null;
        };
        findUniqueOrThrow: {
          args: Prisma.CompanyProfileFindUniqueOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyProfilePayload>;
        };
        findFirst: {
          args: Prisma.CompanyProfileFindFirstArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyProfilePayload> | null;
        };
        findFirstOrThrow: {
          args: Prisma.CompanyProfileFindFirstOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyProfilePayload>;
        };
        findMany: {
          args: Prisma.CompanyProfileFindManyArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyProfilePayload>[];
        };
        create: {
          args: Prisma.CompanyProfileCreateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyProfilePayload>;
        };
        createMany: {
          args: Prisma.CompanyProfileCreateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        createManyAndReturn: {
          args: Prisma.CompanyProfileCreateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyProfilePayload>[];
        };
        delete: {
          args: Prisma.CompanyProfileDeleteArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyProfilePayload>;
        };
        update: {
          args: Prisma.CompanyProfileUpdateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyProfilePayload>;
        };
        deleteMany: {
          args: Prisma.CompanyProfileDeleteManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateMany: {
          args: Prisma.CompanyProfileUpdateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateManyAndReturn: {
          args: Prisma.CompanyProfileUpdateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyProfilePayload>[];
        };
        upsert: {
          args: Prisma.CompanyProfileUpsertArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$CompanyProfilePayload>;
        };
        aggregate: {
          args: Prisma.CompanyProfileAggregateArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.AggregateCompanyProfile>;
        };
        groupBy: {
          args: Prisma.CompanyProfileGroupByArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.CompanyProfileGroupByOutputType>[];
        };
        count: {
          args: Prisma.CompanyProfileCountArgs<ExtArgs>;
          result:
            | runtime.Types.Utils.Optional<Prisma.CompanyProfileCountAggregateOutputType>
            | number;
        };
      };
    };
    Buyer: {
      payload: Prisma.$BuyerPayload<ExtArgs>;
      fields: Prisma.BuyerFieldRefs;
      operations: {
        findUnique: {
          args: Prisma.BuyerFindUniqueArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuyerPayload> | null;
        };
        findUniqueOrThrow: {
          args: Prisma.BuyerFindUniqueOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuyerPayload>;
        };
        findFirst: {
          args: Prisma.BuyerFindFirstArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuyerPayload> | null;
        };
        findFirstOrThrow: {
          args: Prisma.BuyerFindFirstOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuyerPayload>;
        };
        findMany: {
          args: Prisma.BuyerFindManyArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuyerPayload>[];
        };
        create: {
          args: Prisma.BuyerCreateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuyerPayload>;
        };
        createMany: {
          args: Prisma.BuyerCreateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        createManyAndReturn: {
          args: Prisma.BuyerCreateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuyerPayload>[];
        };
        delete: {
          args: Prisma.BuyerDeleteArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuyerPayload>;
        };
        update: {
          args: Prisma.BuyerUpdateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuyerPayload>;
        };
        deleteMany: {
          args: Prisma.BuyerDeleteManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateMany: {
          args: Prisma.BuyerUpdateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateManyAndReturn: {
          args: Prisma.BuyerUpdateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuyerPayload>[];
        };
        upsert: {
          args: Prisma.BuyerUpsertArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$BuyerPayload>;
        };
        aggregate: {
          args: Prisma.BuyerAggregateArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.AggregateBuyer>;
        };
        groupBy: {
          args: Prisma.BuyerGroupByArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.BuyerGroupByOutputType>[];
        };
        count: {
          args: Prisma.BuyerCountArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.BuyerCountAggregateOutputType> | number;
        };
      };
    };
    Product: {
      payload: Prisma.$ProductPayload<ExtArgs>;
      fields: Prisma.ProductFieldRefs;
      operations: {
        findUnique: {
          args: Prisma.ProductFindUniqueArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload> | null;
        };
        findUniqueOrThrow: {
          args: Prisma.ProductFindUniqueOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>;
        };
        findFirst: {
          args: Prisma.ProductFindFirstArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload> | null;
        };
        findFirstOrThrow: {
          args: Prisma.ProductFindFirstOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>;
        };
        findMany: {
          args: Prisma.ProductFindManyArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>[];
        };
        create: {
          args: Prisma.ProductCreateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>;
        };
        createMany: {
          args: Prisma.ProductCreateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        createManyAndReturn: {
          args: Prisma.ProductCreateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>[];
        };
        delete: {
          args: Prisma.ProductDeleteArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>;
        };
        update: {
          args: Prisma.ProductUpdateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>;
        };
        deleteMany: {
          args: Prisma.ProductDeleteManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateMany: {
          args: Prisma.ProductUpdateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateManyAndReturn: {
          args: Prisma.ProductUpdateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>[];
        };
        upsert: {
          args: Prisma.ProductUpsertArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductPayload>;
        };
        aggregate: {
          args: Prisma.ProductAggregateArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.AggregateProduct>;
        };
        groupBy: {
          args: Prisma.ProductGroupByArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.ProductGroupByOutputType>[];
        };
        count: {
          args: Prisma.ProductCountArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.ProductCountAggregateOutputType> | number;
        };
      };
    };
    ProductVariant: {
      payload: Prisma.$ProductVariantPayload<ExtArgs>;
      fields: Prisma.ProductVariantFieldRefs;
      operations: {
        findUnique: {
          args: Prisma.ProductVariantFindUniqueArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductVariantPayload> | null;
        };
        findUniqueOrThrow: {
          args: Prisma.ProductVariantFindUniqueOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductVariantPayload>;
        };
        findFirst: {
          args: Prisma.ProductVariantFindFirstArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductVariantPayload> | null;
        };
        findFirstOrThrow: {
          args: Prisma.ProductVariantFindFirstOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductVariantPayload>;
        };
        findMany: {
          args: Prisma.ProductVariantFindManyArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductVariantPayload>[];
        };
        create: {
          args: Prisma.ProductVariantCreateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductVariantPayload>;
        };
        createMany: {
          args: Prisma.ProductVariantCreateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        createManyAndReturn: {
          args: Prisma.ProductVariantCreateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductVariantPayload>[];
        };
        delete: {
          args: Prisma.ProductVariantDeleteArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductVariantPayload>;
        };
        update: {
          args: Prisma.ProductVariantUpdateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductVariantPayload>;
        };
        deleteMany: {
          args: Prisma.ProductVariantDeleteManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateMany: {
          args: Prisma.ProductVariantUpdateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateManyAndReturn: {
          args: Prisma.ProductVariantUpdateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductVariantPayload>[];
        };
        upsert: {
          args: Prisma.ProductVariantUpsertArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$ProductVariantPayload>;
        };
        aggregate: {
          args: Prisma.ProductVariantAggregateArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.AggregateProductVariant>;
        };
        groupBy: {
          args: Prisma.ProductVariantGroupByArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.ProductVariantGroupByOutputType>[];
        };
        count: {
          args: Prisma.ProductVariantCountArgs<ExtArgs>;
          result:
            | runtime.Types.Utils.Optional<Prisma.ProductVariantCountAggregateOutputType>
            | number;
        };
      };
    };
    Order: {
      payload: Prisma.$OrderPayload<ExtArgs>;
      fields: Prisma.OrderFieldRefs;
      operations: {
        findUnique: {
          args: Prisma.OrderFindUniqueArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderPayload> | null;
        };
        findUniqueOrThrow: {
          args: Prisma.OrderFindUniqueOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderPayload>;
        };
        findFirst: {
          args: Prisma.OrderFindFirstArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderPayload> | null;
        };
        findFirstOrThrow: {
          args: Prisma.OrderFindFirstOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderPayload>;
        };
        findMany: {
          args: Prisma.OrderFindManyArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderPayload>[];
        };
        create: {
          args: Prisma.OrderCreateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderPayload>;
        };
        createMany: {
          args: Prisma.OrderCreateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        createManyAndReturn: {
          args: Prisma.OrderCreateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderPayload>[];
        };
        delete: {
          args: Prisma.OrderDeleteArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderPayload>;
        };
        update: {
          args: Prisma.OrderUpdateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderPayload>;
        };
        deleteMany: {
          args: Prisma.OrderDeleteManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateMany: {
          args: Prisma.OrderUpdateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateManyAndReturn: {
          args: Prisma.OrderUpdateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderPayload>[];
        };
        upsert: {
          args: Prisma.OrderUpsertArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderPayload>;
        };
        aggregate: {
          args: Prisma.OrderAggregateArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.AggregateOrder>;
        };
        groupBy: {
          args: Prisma.OrderGroupByArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.OrderGroupByOutputType>[];
        };
        count: {
          args: Prisma.OrderCountArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.OrderCountAggregateOutputType> | number;
        };
      };
    };
    OrderItem: {
      payload: Prisma.$OrderItemPayload<ExtArgs>;
      fields: Prisma.OrderItemFieldRefs;
      operations: {
        findUnique: {
          args: Prisma.OrderItemFindUniqueArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderItemPayload> | null;
        };
        findUniqueOrThrow: {
          args: Prisma.OrderItemFindUniqueOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderItemPayload>;
        };
        findFirst: {
          args: Prisma.OrderItemFindFirstArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderItemPayload> | null;
        };
        findFirstOrThrow: {
          args: Prisma.OrderItemFindFirstOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderItemPayload>;
        };
        findMany: {
          args: Prisma.OrderItemFindManyArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderItemPayload>[];
        };
        create: {
          args: Prisma.OrderItemCreateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderItemPayload>;
        };
        createMany: {
          args: Prisma.OrderItemCreateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        createManyAndReturn: {
          args: Prisma.OrderItemCreateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderItemPayload>[];
        };
        delete: {
          args: Prisma.OrderItemDeleteArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderItemPayload>;
        };
        update: {
          args: Prisma.OrderItemUpdateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderItemPayload>;
        };
        deleteMany: {
          args: Prisma.OrderItemDeleteManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateMany: {
          args: Prisma.OrderItemUpdateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateManyAndReturn: {
          args: Prisma.OrderItemUpdateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderItemPayload>[];
        };
        upsert: {
          args: Prisma.OrderItemUpsertArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$OrderItemPayload>;
        };
        aggregate: {
          args: Prisma.OrderItemAggregateArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.AggregateOrderItem>;
        };
        groupBy: {
          args: Prisma.OrderItemGroupByArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.OrderItemGroupByOutputType>[];
        };
        count: {
          args: Prisma.OrderItemCountArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.OrderItemCountAggregateOutputType> | number;
        };
      };
    };
    PaymentLedger: {
      payload: Prisma.$PaymentLedgerPayload<ExtArgs>;
      fields: Prisma.PaymentLedgerFieldRefs;
      operations: {
        findUnique: {
          args: Prisma.PaymentLedgerFindUniqueArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentLedgerPayload> | null;
        };
        findUniqueOrThrow: {
          args: Prisma.PaymentLedgerFindUniqueOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentLedgerPayload>;
        };
        findFirst: {
          args: Prisma.PaymentLedgerFindFirstArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentLedgerPayload> | null;
        };
        findFirstOrThrow: {
          args: Prisma.PaymentLedgerFindFirstOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentLedgerPayload>;
        };
        findMany: {
          args: Prisma.PaymentLedgerFindManyArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentLedgerPayload>[];
        };
        create: {
          args: Prisma.PaymentLedgerCreateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentLedgerPayload>;
        };
        createMany: {
          args: Prisma.PaymentLedgerCreateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        createManyAndReturn: {
          args: Prisma.PaymentLedgerCreateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentLedgerPayload>[];
        };
        delete: {
          args: Prisma.PaymentLedgerDeleteArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentLedgerPayload>;
        };
        update: {
          args: Prisma.PaymentLedgerUpdateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentLedgerPayload>;
        };
        deleteMany: {
          args: Prisma.PaymentLedgerDeleteManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateMany: {
          args: Prisma.PaymentLedgerUpdateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateManyAndReturn: {
          args: Prisma.PaymentLedgerUpdateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentLedgerPayload>[];
        };
        upsert: {
          args: Prisma.PaymentLedgerUpsertArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$PaymentLedgerPayload>;
        };
        aggregate: {
          args: Prisma.PaymentLedgerAggregateArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.AggregatePaymentLedger>;
        };
        groupBy: {
          args: Prisma.PaymentLedgerGroupByArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.PaymentLedgerGroupByOutputType>[];
        };
        count: {
          args: Prisma.PaymentLedgerCountArgs<ExtArgs>;
          result:
            | runtime.Types.Utils.Optional<Prisma.PaymentLedgerCountAggregateOutputType>
            | number;
        };
      };
    };
    DocumentAttachment: {
      payload: Prisma.$DocumentAttachmentPayload<ExtArgs>;
      fields: Prisma.DocumentAttachmentFieldRefs;
      operations: {
        findUnique: {
          args: Prisma.DocumentAttachmentFindUniqueArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentAttachmentPayload> | null;
        };
        findUniqueOrThrow: {
          args: Prisma.DocumentAttachmentFindUniqueOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentAttachmentPayload>;
        };
        findFirst: {
          args: Prisma.DocumentAttachmentFindFirstArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentAttachmentPayload> | null;
        };
        findFirstOrThrow: {
          args: Prisma.DocumentAttachmentFindFirstOrThrowArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentAttachmentPayload>;
        };
        findMany: {
          args: Prisma.DocumentAttachmentFindManyArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentAttachmentPayload>[];
        };
        create: {
          args: Prisma.DocumentAttachmentCreateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentAttachmentPayload>;
        };
        createMany: {
          args: Prisma.DocumentAttachmentCreateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        createManyAndReturn: {
          args: Prisma.DocumentAttachmentCreateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentAttachmentPayload>[];
        };
        delete: {
          args: Prisma.DocumentAttachmentDeleteArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentAttachmentPayload>;
        };
        update: {
          args: Prisma.DocumentAttachmentUpdateArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentAttachmentPayload>;
        };
        deleteMany: {
          args: Prisma.DocumentAttachmentDeleteManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateMany: {
          args: Prisma.DocumentAttachmentUpdateManyArgs<ExtArgs>;
          result: BatchPayload;
        };
        updateManyAndReturn: {
          args: Prisma.DocumentAttachmentUpdateManyAndReturnArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentAttachmentPayload>[];
        };
        upsert: {
          args: Prisma.DocumentAttachmentUpsertArgs<ExtArgs>;
          result: runtime.Types.Utils.PayloadToResult<Prisma.$DocumentAttachmentPayload>;
        };
        aggregate: {
          args: Prisma.DocumentAttachmentAggregateArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.AggregateDocumentAttachment>;
        };
        groupBy: {
          args: Prisma.DocumentAttachmentGroupByArgs<ExtArgs>;
          result: runtime.Types.Utils.Optional<Prisma.DocumentAttachmentGroupByOutputType>[];
        };
        count: {
          args: Prisma.DocumentAttachmentCountArgs<ExtArgs>;
          result:
            | runtime.Types.Utils.Optional<Prisma.DocumentAttachmentCountAggregateOutputType>
            | number;
        };
      };
    };
  };
} & {
  other: {
    payload: any;
    operations: {
      $executeRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]];
        result: any;
      };
      $executeRawUnsafe: {
        args: [query: string, ...values: any[]];
        result: any;
      };
      $queryRaw: {
        args: [query: TemplateStringsArray | Sql, ...values: any[]];
        result: any;
      };
      $queryRawUnsafe: {
        args: [query: string, ...values: any[]];
        result: any;
      };
    };
  };
};

/**
 * Enums
 */

export const TransactionIsolationLevel = runtime.makeStrictEnum({
  ReadUncommitted: 'ReadUncommitted',
  ReadCommitted: 'ReadCommitted',
  RepeatableRead: 'RepeatableRead',
  Serializable: 'Serializable',
} as const);

export type TransactionIsolationLevel =
  (typeof TransactionIsolationLevel)[keyof typeof TransactionIsolationLevel];

export const CompanyProfileScalarFieldEnum = {
  id: 'id',
  companyName: 'companyName',
  addressLine1: 'addressLine1',
  addressLine2: 'addressLine2',
  city: 'city',
  district: 'district',
  state: 'state',
  stateCode: 'stateCode',
  pincode: 'pincode',
  gstin: 'gstin',
  iecCode: 'iecCode',
  pan: 'pan',
  lutNumber: 'lutNumber',
  llpin: 'llpin',
  adCode: 'adCode',
  bankName: 'bankName',
  bankBranch: 'bankBranch',
  bankAddress: 'bankAddress',
  accountName: 'accountName',
  accountNumber: 'accountNumber',
  swiftCode: 'swiftCode',
  ifscCode: 'ifscCode',
  email: 'email',
  phone: 'phone',
  website: 'website',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type CompanyProfileScalarFieldEnum =
  (typeof CompanyProfileScalarFieldEnum)[keyof typeof CompanyProfileScalarFieldEnum];

export const BuyerScalarFieldEnum = {
  id: 'id',
  companyName: 'companyName',
  contactPerson: 'contactPerson',
  billingAddress: 'billingAddress',
  shippingAddress: 'shippingAddress',
  country: 'country',
  taxId: 'taxId',
  preferredCurrency: 'preferredCurrency',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type BuyerScalarFieldEnum = (typeof BuyerScalarFieldEnum)[keyof typeof BuyerScalarFieldEnum];

export const ProductScalarFieldEnum = {
  id: 'id',
  skuBase: 'skuBase',
  description: 'description',
  hsCode: 'hsCode',
  unitPriceUsd: 'unitPriceUsd',
  moq: 'moq',
  weightNet: 'weightNet',
  weightGross: 'weightGross',
  cbm: 'cbm',
  createdAt: 'createdAt',
} as const;

export type ProductScalarFieldEnum =
  (typeof ProductScalarFieldEnum)[keyof typeof ProductScalarFieldEnum];

export const ProductVariantScalarFieldEnum = {
  id: 'id',
  productId: 'productId',
  skuFull: 'skuFull',
  color: 'color',
  leatherType: 'leatherType',
  stockAllocation: 'stockAllocation',
} as const;

export type ProductVariantScalarFieldEnum =
  (typeof ProductVariantScalarFieldEnum)[keyof typeof ProductVariantScalarFieldEnum];

export const OrderScalarFieldEnum = {
  id: 'id',
  documentNumber: 'documentNumber',
  status: 'status',
  buyerId: 'buyerId',
  incoterm: 'incoterm',
  portOfLoading: 'portOfLoading',
  portOfDischarge: 'portOfDischarge',
  vesselName: 'vesselName',
  awbBlNumber: 'awbBlNumber',
  shippingBillNumber: 'shippingBillNumber',
  shippingBillDate: 'shippingBillDate',
  currency: 'currency',
  subTotal: 'subTotal',
  freightCost: 'freightCost',
  insuranceCost: 'insuranceCost',
  grandTotal: 'grandTotal',
  lockedExchangeRate: 'lockedExchangeRate',
  appliedLutNumber: 'appliedLutNumber',
  createdAt: 'createdAt',
  updatedAt: 'updatedAt',
} as const;

export type OrderScalarFieldEnum = (typeof OrderScalarFieldEnum)[keyof typeof OrderScalarFieldEnum];

export const OrderItemScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  variantId: 'variantId',
  skuFull: 'skuFull',
  quantity: 'quantity',
  historicalUnitPrice: 'historicalUnitPrice',
  historicalDescription: 'historicalDescription',
  historicalHsCode: 'historicalHsCode',
  historicalNetWeight: 'historicalNetWeight',
  historicalGrossWeight: 'historicalGrossWeight',
  historicalCbm: 'historicalCbm',
  lineTotal: 'lineTotal',
} as const;

export type OrderItemScalarFieldEnum =
  (typeof OrderItemScalarFieldEnum)[keyof typeof OrderItemScalarFieldEnum];

export const PaymentLedgerScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  amount: 'amount',
  currency: 'currency',
  exchangeRate: 'exchangeRate',
  paymentType: 'paymentType',
  paymentDate: 'paymentDate',
  referenceId: 'referenceId',
  eBrcNumber: 'eBrcNumber',
  eBrcDate: 'eBrcDate',
  bankFircNumber: 'bankFircNumber',
} as const;

export type PaymentLedgerScalarFieldEnum =
  (typeof PaymentLedgerScalarFieldEnum)[keyof typeof PaymentLedgerScalarFieldEnum];

export const DocumentAttachmentScalarFieldEnum = {
  id: 'id',
  orderId: 'orderId',
  fileName: 'fileName',
  s3ObjectKey: 's3ObjectKey',
  fileType: 'fileType',
  createdAt: 'createdAt',
} as const;

export type DocumentAttachmentScalarFieldEnum =
  (typeof DocumentAttachmentScalarFieldEnum)[keyof typeof DocumentAttachmentScalarFieldEnum];

export const SortOrder = {
  asc: 'asc',
  desc: 'desc',
} as const;

export type SortOrder = (typeof SortOrder)[keyof typeof SortOrder];

export const QueryMode = {
  default: 'default',
  insensitive: 'insensitive',
} as const;

export type QueryMode = (typeof QueryMode)[keyof typeof QueryMode];

export const NullsOrder = {
  first: 'first',
  last: 'last',
} as const;

export type NullsOrder = (typeof NullsOrder)[keyof typeof NullsOrder];

/**
 * Field references
 */

/**
 * Reference to a field of type 'String'
 */
export type StringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String'>;

/**
 * Reference to a field of type 'String[]'
 */
export type ListStringFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'String[]'>;

/**
 * Reference to a field of type 'DateTime'
 */
export type DateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime'>;

/**
 * Reference to a field of type 'DateTime[]'
 */
export type ListDateTimeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'DateTime[]'>;

/**
 * Reference to a field of type 'Float'
 */
export type FloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float'>;

/**
 * Reference to a field of type 'Float[]'
 */
export type ListFloatFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Float[]'>;

/**
 * Reference to a field of type 'Int'
 */
export type IntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int'>;

/**
 * Reference to a field of type 'Int[]'
 */
export type ListIntFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Int[]'>;

/**
 * Reference to a field of type 'OrderStatus'
 */
export type EnumOrderStatusFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'OrderStatus'
>;

/**
 * Reference to a field of type 'OrderStatus[]'
 */
export type ListEnumOrderStatusFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'OrderStatus[]'
>;

/**
 * Reference to a field of type 'Incoterm'
 */
export type EnumIncotermFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'Incoterm'>;

/**
 * Reference to a field of type 'Incoterm[]'
 */
export type ListEnumIncotermFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'Incoterm[]'
>;

/**
 * Reference to a field of type 'PaymentType'
 */
export type EnumPaymentTypeFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'PaymentType'
>;

/**
 * Reference to a field of type 'PaymentType[]'
 */
export type ListEnumPaymentTypeFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'PaymentType[]'
>;

/**
 * Reference to a field of type 'FileType'
 */
export type EnumFileTypeFieldRefInput<$PrismaModel> = FieldRefInputType<$PrismaModel, 'FileType'>;

/**
 * Reference to a field of type 'FileType[]'
 */
export type ListEnumFileTypeFieldRefInput<$PrismaModel> = FieldRefInputType<
  $PrismaModel,
  'FileType[]'
>;

/**
 * Batch Payload for updateMany & deleteMany & createMany
 */
export type BatchPayload = {
  count: number;
};

export const defineExtension = runtime.Extensions
  .defineExtension as unknown as runtime.Types.Extensions.ExtendsHook<
  'define',
  TypeMapCb,
  runtime.Types.Extensions.DefaultArgs
>;
export type DefaultPrismaClient = PrismaClient;
export type ErrorFormat = 'pretty' | 'colorless' | 'minimal';
export type PrismaClientOptions = (
  | {
      /**
       * Instance of a Driver Adapter, e.g., like one provided by `@prisma/adapter-pg`.
       */
      adapter: runtime.SqlDriverAdapterFactory;
      accelerateUrl?: never;
    }
  | {
      /**
       * Prisma Accelerate URL allowing the client to connect through Accelerate instead of a direct database.
       */
      accelerateUrl: string;
      adapter?: never;
    }
) & {
  /**
   * @default "colorless"
   */
  errorFormat?: ErrorFormat;
  /**
   * @example
   * ```
   * // Shorthand for `emit: 'stdout'`
   * log: ['query', 'info', 'warn', 'error']
   *
   * // Emit as events only
   * log: [
   *   { emit: 'event', level: 'query' },
   *   { emit: 'event', level: 'info' },
   *   { emit: 'event', level: 'warn' }
   *   { emit: 'event', level: 'error' }
   * ]
   *
   * / Emit as events and log to stdout
   * og: [
   *  { emit: 'stdout', level: 'query' },
   *  { emit: 'stdout', level: 'info' },
   *  { emit: 'stdout', level: 'warn' }
   *  { emit: 'stdout', level: 'error' }
   *
   * ```
   * Read more in our [docs](https://pris.ly/d/logging).
   */
  log?: (LogLevel | LogDefinition)[];
  /**
   * The default values for transactionOptions
   * maxWait ?= 2000
   * timeout ?= 5000
   */
  transactionOptions?: {
    maxWait?: number;
    timeout?: number;
    isolationLevel?: TransactionIsolationLevel;
  };
  /**
   * Global configuration for omitting model fields by default.
   *
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   omit: {
   *     user: {
   *       password: true
   *     }
   *   }
   * })
   * ```
   */
  omit?: GlobalOmitConfig;
  /**
   * SQL commenter plugins that add metadata to SQL queries as comments.
   * Comments follow the sqlcommenter format: https://google.github.io/sqlcommenter/
   *
   * @example
   * ```
   * const prisma = new PrismaClient({
   *   adapter,
   *   comments: [
   *     traceContext(),
   *     queryInsights(),
   *   ],
   * })
   * ```
   */
  comments?: runtime.SqlCommenterPlugin[];
};
export type GlobalOmitConfig = {
  companyProfile?: Prisma.CompanyProfileOmit;
  buyer?: Prisma.BuyerOmit;
  product?: Prisma.ProductOmit;
  productVariant?: Prisma.ProductVariantOmit;
  order?: Prisma.OrderOmit;
  orderItem?: Prisma.OrderItemOmit;
  paymentLedger?: Prisma.PaymentLedgerOmit;
  documentAttachment?: Prisma.DocumentAttachmentOmit;
};

/* Types for Logging */
export type LogLevel = 'info' | 'query' | 'warn' | 'error';
export type LogDefinition = {
  level: LogLevel;
  emit: 'stdout' | 'event';
};

export type CheckIsLogLevel<T> = T extends LogLevel ? T : never;

export type GetLogType<T> = CheckIsLogLevel<T extends LogDefinition ? T['level'] : T>;

export type GetEvents<T extends any[]> =
  T extends Array<LogLevel | LogDefinition> ? GetLogType<T[number]> : never;

export type QueryEvent = {
  timestamp: Date;
  query: string;
  params: string;
  duration: number;
  target: string;
};

export type LogEvent = {
  timestamp: Date;
  message: string;
  target: string;
};
/* End Types for Logging */

export type PrismaAction =
  | 'findUnique'
  | 'findUniqueOrThrow'
  | 'findMany'
  | 'findFirst'
  | 'findFirstOrThrow'
  | 'create'
  | 'createMany'
  | 'createManyAndReturn'
  | 'update'
  | 'updateMany'
  | 'updateManyAndReturn'
  | 'upsert'
  | 'delete'
  | 'deleteMany'
  | 'executeRaw'
  | 'queryRaw'
  | 'aggregate'
  | 'count'
  | 'runCommandRaw'
  | 'findRaw'
  | 'groupBy';

/**
 * `PrismaClient` proxy available in interactive transactions.
 */
export type TransactionClient = Omit<DefaultPrismaClient, runtime.ITXClientDenyList>;
