
/* !!! This is code generated by Prisma. Do not edit directly. !!! */
/* eslint-disable */
// biome-ignore-all lint: generated file
// @ts-nocheck 
/*
 * This file exports the `PaymentLedger` model and its related types.
 *
 * 🟢 You can import this file directly.
 */
import type * as runtime from "@prisma/client/runtime/client"
import type * as $Enums from "../enums"
import type * as Prisma from "../internal/prismaNamespace"

/**
 * Model PaymentLedger
 * 
 */
export type PaymentLedgerModel = runtime.Types.Result.DefaultSelection<Prisma.$PaymentLedgerPayload>

export type AggregatePaymentLedger = {
  _count: PaymentLedgerCountAggregateOutputType | null
  _avg: PaymentLedgerAvgAggregateOutputType | null
  _sum: PaymentLedgerSumAggregateOutputType | null
  _min: PaymentLedgerMinAggregateOutputType | null
  _max: PaymentLedgerMaxAggregateOutputType | null
}

export type PaymentLedgerAvgAggregateOutputType = {
  amount: number | null
  exchangeRate: number | null
}

export type PaymentLedgerSumAggregateOutputType = {
  amount: number | null
  exchangeRate: number | null
}

export type PaymentLedgerMinAggregateOutputType = {
  id: string | null
  orderId: string | null
  amount: number | null
  currency: string | null
  exchangeRate: number | null
  paymentType: $Enums.PaymentType | null
  paymentDate: Date | null
  referenceId: string | null
  eBrcNumber: string | null
  eBrcDate: Date | null
  bankFircNumber: string | null
}

export type PaymentLedgerMaxAggregateOutputType = {
  id: string | null
  orderId: string | null
  amount: number | null
  currency: string | null
  exchangeRate: number | null
  paymentType: $Enums.PaymentType | null
  paymentDate: Date | null
  referenceId: string | null
  eBrcNumber: string | null
  eBrcDate: Date | null
  bankFircNumber: string | null
}

export type PaymentLedgerCountAggregateOutputType = {
  id: number
  orderId: number
  amount: number
  currency: number
  exchangeRate: number
  paymentType: number
  paymentDate: number
  referenceId: number
  eBrcNumber: number
  eBrcDate: number
  bankFircNumber: number
  _all: number
}


export type PaymentLedgerAvgAggregateInputType = {
  amount?: true
  exchangeRate?: true
}

export type PaymentLedgerSumAggregateInputType = {
  amount?: true
  exchangeRate?: true
}

export type PaymentLedgerMinAggregateInputType = {
  id?: true
  orderId?: true
  amount?: true
  currency?: true
  exchangeRate?: true
  paymentType?: true
  paymentDate?: true
  referenceId?: true
  eBrcNumber?: true
  eBrcDate?: true
  bankFircNumber?: true
}

export type PaymentLedgerMaxAggregateInputType = {
  id?: true
  orderId?: true
  amount?: true
  currency?: true
  exchangeRate?: true
  paymentType?: true
  paymentDate?: true
  referenceId?: true
  eBrcNumber?: true
  eBrcDate?: true
  bankFircNumber?: true
}

export type PaymentLedgerCountAggregateInputType = {
  id?: true
  orderId?: true
  amount?: true
  currency?: true
  exchangeRate?: true
  paymentType?: true
  paymentDate?: true
  referenceId?: true
  eBrcNumber?: true
  eBrcDate?: true
  bankFircNumber?: true
  _all?: true
}

export type PaymentLedgerAggregateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PaymentLedger to aggregate.
   */
  where?: Prisma.PaymentLedgerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaymentLedgers to fetch.
   */
  orderBy?: Prisma.PaymentLedgerOrderByWithRelationInput | Prisma.PaymentLedgerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the start position
   */
  cursor?: Prisma.PaymentLedgerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaymentLedgers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaymentLedgers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Count returned PaymentLedgers
  **/
  _count?: true | PaymentLedgerCountAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to average
  **/
  _avg?: PaymentLedgerAvgAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to sum
  **/
  _sum?: PaymentLedgerSumAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the minimum value
  **/
  _min?: PaymentLedgerMinAggregateInputType
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/aggregations Aggregation Docs}
   * 
   * Select which fields to find the maximum value
  **/
  _max?: PaymentLedgerMaxAggregateInputType
}

export type GetPaymentLedgerAggregateType<T extends PaymentLedgerAggregateArgs> = {
      [P in keyof T & keyof AggregatePaymentLedger]: P extends '_count' | 'count'
    ? T[P] extends true
      ? number
      : Prisma.GetScalarType<T[P], AggregatePaymentLedger[P]>
    : Prisma.GetScalarType<T[P], AggregatePaymentLedger[P]>
}




export type PaymentLedgerGroupByArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  where?: Prisma.PaymentLedgerWhereInput
  orderBy?: Prisma.PaymentLedgerOrderByWithAggregationInput | Prisma.PaymentLedgerOrderByWithAggregationInput[]
  by: Prisma.PaymentLedgerScalarFieldEnum[] | Prisma.PaymentLedgerScalarFieldEnum
  having?: Prisma.PaymentLedgerScalarWhereWithAggregatesInput
  take?: number
  skip?: number
  _count?: PaymentLedgerCountAggregateInputType | true
  _avg?: PaymentLedgerAvgAggregateInputType
  _sum?: PaymentLedgerSumAggregateInputType
  _min?: PaymentLedgerMinAggregateInputType
  _max?: PaymentLedgerMaxAggregateInputType
}

export type PaymentLedgerGroupByOutputType = {
  id: string
  orderId: string
  amount: number
  currency: string
  exchangeRate: number
  paymentType: $Enums.PaymentType
  paymentDate: Date
  referenceId: string | null
  eBrcNumber: string | null
  eBrcDate: Date | null
  bankFircNumber: string | null
  _count: PaymentLedgerCountAggregateOutputType | null
  _avg: PaymentLedgerAvgAggregateOutputType | null
  _sum: PaymentLedgerSumAggregateOutputType | null
  _min: PaymentLedgerMinAggregateOutputType | null
  _max: PaymentLedgerMaxAggregateOutputType | null
}

export type GetPaymentLedgerGroupByPayload<T extends PaymentLedgerGroupByArgs> = Prisma.PrismaPromise<
  Array<
    Prisma.PickEnumerable<PaymentLedgerGroupByOutputType, T['by']> &
      {
        [P in ((keyof T) & (keyof PaymentLedgerGroupByOutputType))]: P extends '_count'
          ? T[P] extends boolean
            ? number
            : Prisma.GetScalarType<T[P], PaymentLedgerGroupByOutputType[P]>
          : Prisma.GetScalarType<T[P], PaymentLedgerGroupByOutputType[P]>
      }
    >
  >



export type PaymentLedgerWhereInput = {
  AND?: Prisma.PaymentLedgerWhereInput | Prisma.PaymentLedgerWhereInput[]
  OR?: Prisma.PaymentLedgerWhereInput[]
  NOT?: Prisma.PaymentLedgerWhereInput | Prisma.PaymentLedgerWhereInput[]
  id?: Prisma.StringFilter<"PaymentLedger"> | string
  orderId?: Prisma.StringFilter<"PaymentLedger"> | string
  amount?: Prisma.FloatFilter<"PaymentLedger"> | number
  currency?: Prisma.StringFilter<"PaymentLedger"> | string
  exchangeRate?: Prisma.FloatFilter<"PaymentLedger"> | number
  paymentType?: Prisma.EnumPaymentTypeFilter<"PaymentLedger"> | $Enums.PaymentType
  paymentDate?: Prisma.DateTimeFilter<"PaymentLedger"> | Date | string
  referenceId?: Prisma.StringNullableFilter<"PaymentLedger"> | string | null
  eBrcNumber?: Prisma.StringNullableFilter<"PaymentLedger"> | string | null
  eBrcDate?: Prisma.DateTimeNullableFilter<"PaymentLedger"> | Date | string | null
  bankFircNumber?: Prisma.StringNullableFilter<"PaymentLedger"> | string | null
  order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
}

export type PaymentLedgerOrderByWithRelationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  exchangeRate?: Prisma.SortOrder
  paymentType?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  referenceId?: Prisma.SortOrderInput | Prisma.SortOrder
  eBrcNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  eBrcDate?: Prisma.SortOrderInput | Prisma.SortOrder
  bankFircNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  order?: Prisma.OrderOrderByWithRelationInput
}

export type PaymentLedgerWhereUniqueInput = Prisma.AtLeast<{
  id?: string
  AND?: Prisma.PaymentLedgerWhereInput | Prisma.PaymentLedgerWhereInput[]
  OR?: Prisma.PaymentLedgerWhereInput[]
  NOT?: Prisma.PaymentLedgerWhereInput | Prisma.PaymentLedgerWhereInput[]
  orderId?: Prisma.StringFilter<"PaymentLedger"> | string
  amount?: Prisma.FloatFilter<"PaymentLedger"> | number
  currency?: Prisma.StringFilter<"PaymentLedger"> | string
  exchangeRate?: Prisma.FloatFilter<"PaymentLedger"> | number
  paymentType?: Prisma.EnumPaymentTypeFilter<"PaymentLedger"> | $Enums.PaymentType
  paymentDate?: Prisma.DateTimeFilter<"PaymentLedger"> | Date | string
  referenceId?: Prisma.StringNullableFilter<"PaymentLedger"> | string | null
  eBrcNumber?: Prisma.StringNullableFilter<"PaymentLedger"> | string | null
  eBrcDate?: Prisma.DateTimeNullableFilter<"PaymentLedger"> | Date | string | null
  bankFircNumber?: Prisma.StringNullableFilter<"PaymentLedger"> | string | null
  order?: Prisma.XOR<Prisma.OrderScalarRelationFilter, Prisma.OrderWhereInput>
}, "id">

export type PaymentLedgerOrderByWithAggregationInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  exchangeRate?: Prisma.SortOrder
  paymentType?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  referenceId?: Prisma.SortOrderInput | Prisma.SortOrder
  eBrcNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  eBrcDate?: Prisma.SortOrderInput | Prisma.SortOrder
  bankFircNumber?: Prisma.SortOrderInput | Prisma.SortOrder
  _count?: Prisma.PaymentLedgerCountOrderByAggregateInput
  _avg?: Prisma.PaymentLedgerAvgOrderByAggregateInput
  _max?: Prisma.PaymentLedgerMaxOrderByAggregateInput
  _min?: Prisma.PaymentLedgerMinOrderByAggregateInput
  _sum?: Prisma.PaymentLedgerSumOrderByAggregateInput
}

export type PaymentLedgerScalarWhereWithAggregatesInput = {
  AND?: Prisma.PaymentLedgerScalarWhereWithAggregatesInput | Prisma.PaymentLedgerScalarWhereWithAggregatesInput[]
  OR?: Prisma.PaymentLedgerScalarWhereWithAggregatesInput[]
  NOT?: Prisma.PaymentLedgerScalarWhereWithAggregatesInput | Prisma.PaymentLedgerScalarWhereWithAggregatesInput[]
  id?: Prisma.StringWithAggregatesFilter<"PaymentLedger"> | string
  orderId?: Prisma.StringWithAggregatesFilter<"PaymentLedger"> | string
  amount?: Prisma.FloatWithAggregatesFilter<"PaymentLedger"> | number
  currency?: Prisma.StringWithAggregatesFilter<"PaymentLedger"> | string
  exchangeRate?: Prisma.FloatWithAggregatesFilter<"PaymentLedger"> | number
  paymentType?: Prisma.EnumPaymentTypeWithAggregatesFilter<"PaymentLedger"> | $Enums.PaymentType
  paymentDate?: Prisma.DateTimeWithAggregatesFilter<"PaymentLedger"> | Date | string
  referenceId?: Prisma.StringNullableWithAggregatesFilter<"PaymentLedger"> | string | null
  eBrcNumber?: Prisma.StringNullableWithAggregatesFilter<"PaymentLedger"> | string | null
  eBrcDate?: Prisma.DateTimeNullableWithAggregatesFilter<"PaymentLedger"> | Date | string | null
  bankFircNumber?: Prisma.StringNullableWithAggregatesFilter<"PaymentLedger"> | string | null
}

export type PaymentLedgerCreateInput = {
  id?: string
  amount: number
  currency: string
  exchangeRate: number
  paymentType: $Enums.PaymentType
  paymentDate: Date | string
  referenceId?: string | null
  eBrcNumber?: string | null
  eBrcDate?: Date | string | null
  bankFircNumber?: string | null
  order: Prisma.OrderCreateNestedOneWithoutPaymentsInput
}

export type PaymentLedgerUncheckedCreateInput = {
  id?: string
  orderId: string
  amount: number
  currency: string
  exchangeRate: number
  paymentType: $Enums.PaymentType
  paymentDate: Date | string
  referenceId?: string | null
  eBrcNumber?: string | null
  eBrcDate?: Date | string | null
  bankFircNumber?: string | null
}

export type PaymentLedgerUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  exchangeRate?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentType?: Prisma.EnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bankFircNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  order?: Prisma.OrderUpdateOneRequiredWithoutPaymentsNestedInput
}

export type PaymentLedgerUncheckedUpdateInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  exchangeRate?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentType?: Prisma.EnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bankFircNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PaymentLedgerCreateManyInput = {
  id?: string
  orderId: string
  amount: number
  currency: string
  exchangeRate: number
  paymentType: $Enums.PaymentType
  paymentDate: Date | string
  referenceId?: string | null
  eBrcNumber?: string | null
  eBrcDate?: Date | string | null
  bankFircNumber?: string | null
}

export type PaymentLedgerUpdateManyMutationInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  exchangeRate?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentType?: Prisma.EnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bankFircNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PaymentLedgerUncheckedUpdateManyInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  orderId?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  exchangeRate?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentType?: Prisma.EnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bankFircNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PaymentLedgerListRelationFilter = {
  every?: Prisma.PaymentLedgerWhereInput
  some?: Prisma.PaymentLedgerWhereInput
  none?: Prisma.PaymentLedgerWhereInput
}

export type PaymentLedgerOrderByRelationAggregateInput = {
  _count?: Prisma.SortOrder
}

export type PaymentLedgerCountOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  exchangeRate?: Prisma.SortOrder
  paymentType?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  referenceId?: Prisma.SortOrder
  eBrcNumber?: Prisma.SortOrder
  eBrcDate?: Prisma.SortOrder
  bankFircNumber?: Prisma.SortOrder
}

export type PaymentLedgerAvgOrderByAggregateInput = {
  amount?: Prisma.SortOrder
  exchangeRate?: Prisma.SortOrder
}

export type PaymentLedgerMaxOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  exchangeRate?: Prisma.SortOrder
  paymentType?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  referenceId?: Prisma.SortOrder
  eBrcNumber?: Prisma.SortOrder
  eBrcDate?: Prisma.SortOrder
  bankFircNumber?: Prisma.SortOrder
}

export type PaymentLedgerMinOrderByAggregateInput = {
  id?: Prisma.SortOrder
  orderId?: Prisma.SortOrder
  amount?: Prisma.SortOrder
  currency?: Prisma.SortOrder
  exchangeRate?: Prisma.SortOrder
  paymentType?: Prisma.SortOrder
  paymentDate?: Prisma.SortOrder
  referenceId?: Prisma.SortOrder
  eBrcNumber?: Prisma.SortOrder
  eBrcDate?: Prisma.SortOrder
  bankFircNumber?: Prisma.SortOrder
}

export type PaymentLedgerSumOrderByAggregateInput = {
  amount?: Prisma.SortOrder
  exchangeRate?: Prisma.SortOrder
}

export type PaymentLedgerCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.PaymentLedgerCreateWithoutOrderInput, Prisma.PaymentLedgerUncheckedCreateWithoutOrderInput> | Prisma.PaymentLedgerCreateWithoutOrderInput[] | Prisma.PaymentLedgerUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.PaymentLedgerCreateOrConnectWithoutOrderInput | Prisma.PaymentLedgerCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.PaymentLedgerCreateManyOrderInputEnvelope
  connect?: Prisma.PaymentLedgerWhereUniqueInput | Prisma.PaymentLedgerWhereUniqueInput[]
}

export type PaymentLedgerUncheckedCreateNestedManyWithoutOrderInput = {
  create?: Prisma.XOR<Prisma.PaymentLedgerCreateWithoutOrderInput, Prisma.PaymentLedgerUncheckedCreateWithoutOrderInput> | Prisma.PaymentLedgerCreateWithoutOrderInput[] | Prisma.PaymentLedgerUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.PaymentLedgerCreateOrConnectWithoutOrderInput | Prisma.PaymentLedgerCreateOrConnectWithoutOrderInput[]
  createMany?: Prisma.PaymentLedgerCreateManyOrderInputEnvelope
  connect?: Prisma.PaymentLedgerWhereUniqueInput | Prisma.PaymentLedgerWhereUniqueInput[]
}

export type PaymentLedgerUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.PaymentLedgerCreateWithoutOrderInput, Prisma.PaymentLedgerUncheckedCreateWithoutOrderInput> | Prisma.PaymentLedgerCreateWithoutOrderInput[] | Prisma.PaymentLedgerUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.PaymentLedgerCreateOrConnectWithoutOrderInput | Prisma.PaymentLedgerCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.PaymentLedgerUpsertWithWhereUniqueWithoutOrderInput | Prisma.PaymentLedgerUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.PaymentLedgerCreateManyOrderInputEnvelope
  set?: Prisma.PaymentLedgerWhereUniqueInput | Prisma.PaymentLedgerWhereUniqueInput[]
  disconnect?: Prisma.PaymentLedgerWhereUniqueInput | Prisma.PaymentLedgerWhereUniqueInput[]
  delete?: Prisma.PaymentLedgerWhereUniqueInput | Prisma.PaymentLedgerWhereUniqueInput[]
  connect?: Prisma.PaymentLedgerWhereUniqueInput | Prisma.PaymentLedgerWhereUniqueInput[]
  update?: Prisma.PaymentLedgerUpdateWithWhereUniqueWithoutOrderInput | Prisma.PaymentLedgerUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.PaymentLedgerUpdateManyWithWhereWithoutOrderInput | Prisma.PaymentLedgerUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.PaymentLedgerScalarWhereInput | Prisma.PaymentLedgerScalarWhereInput[]
}

export type PaymentLedgerUncheckedUpdateManyWithoutOrderNestedInput = {
  create?: Prisma.XOR<Prisma.PaymentLedgerCreateWithoutOrderInput, Prisma.PaymentLedgerUncheckedCreateWithoutOrderInput> | Prisma.PaymentLedgerCreateWithoutOrderInput[] | Prisma.PaymentLedgerUncheckedCreateWithoutOrderInput[]
  connectOrCreate?: Prisma.PaymentLedgerCreateOrConnectWithoutOrderInput | Prisma.PaymentLedgerCreateOrConnectWithoutOrderInput[]
  upsert?: Prisma.PaymentLedgerUpsertWithWhereUniqueWithoutOrderInput | Prisma.PaymentLedgerUpsertWithWhereUniqueWithoutOrderInput[]
  createMany?: Prisma.PaymentLedgerCreateManyOrderInputEnvelope
  set?: Prisma.PaymentLedgerWhereUniqueInput | Prisma.PaymentLedgerWhereUniqueInput[]
  disconnect?: Prisma.PaymentLedgerWhereUniqueInput | Prisma.PaymentLedgerWhereUniqueInput[]
  delete?: Prisma.PaymentLedgerWhereUniqueInput | Prisma.PaymentLedgerWhereUniqueInput[]
  connect?: Prisma.PaymentLedgerWhereUniqueInput | Prisma.PaymentLedgerWhereUniqueInput[]
  update?: Prisma.PaymentLedgerUpdateWithWhereUniqueWithoutOrderInput | Prisma.PaymentLedgerUpdateWithWhereUniqueWithoutOrderInput[]
  updateMany?: Prisma.PaymentLedgerUpdateManyWithWhereWithoutOrderInput | Prisma.PaymentLedgerUpdateManyWithWhereWithoutOrderInput[]
  deleteMany?: Prisma.PaymentLedgerScalarWhereInput | Prisma.PaymentLedgerScalarWhereInput[]
}

export type EnumPaymentTypeFieldUpdateOperationsInput = {
  set?: $Enums.PaymentType
}

export type PaymentLedgerCreateWithoutOrderInput = {
  id?: string
  amount: number
  currency: string
  exchangeRate: number
  paymentType: $Enums.PaymentType
  paymentDate: Date | string
  referenceId?: string | null
  eBrcNumber?: string | null
  eBrcDate?: Date | string | null
  bankFircNumber?: string | null
}

export type PaymentLedgerUncheckedCreateWithoutOrderInput = {
  id?: string
  amount: number
  currency: string
  exchangeRate: number
  paymentType: $Enums.PaymentType
  paymentDate: Date | string
  referenceId?: string | null
  eBrcNumber?: string | null
  eBrcDate?: Date | string | null
  bankFircNumber?: string | null
}

export type PaymentLedgerCreateOrConnectWithoutOrderInput = {
  where: Prisma.PaymentLedgerWhereUniqueInput
  create: Prisma.XOR<Prisma.PaymentLedgerCreateWithoutOrderInput, Prisma.PaymentLedgerUncheckedCreateWithoutOrderInput>
}

export type PaymentLedgerCreateManyOrderInputEnvelope = {
  data: Prisma.PaymentLedgerCreateManyOrderInput | Prisma.PaymentLedgerCreateManyOrderInput[]
  skipDuplicates?: boolean
}

export type PaymentLedgerUpsertWithWhereUniqueWithoutOrderInput = {
  where: Prisma.PaymentLedgerWhereUniqueInput
  update: Prisma.XOR<Prisma.PaymentLedgerUpdateWithoutOrderInput, Prisma.PaymentLedgerUncheckedUpdateWithoutOrderInput>
  create: Prisma.XOR<Prisma.PaymentLedgerCreateWithoutOrderInput, Prisma.PaymentLedgerUncheckedCreateWithoutOrderInput>
}

export type PaymentLedgerUpdateWithWhereUniqueWithoutOrderInput = {
  where: Prisma.PaymentLedgerWhereUniqueInput
  data: Prisma.XOR<Prisma.PaymentLedgerUpdateWithoutOrderInput, Prisma.PaymentLedgerUncheckedUpdateWithoutOrderInput>
}

export type PaymentLedgerUpdateManyWithWhereWithoutOrderInput = {
  where: Prisma.PaymentLedgerScalarWhereInput
  data: Prisma.XOR<Prisma.PaymentLedgerUpdateManyMutationInput, Prisma.PaymentLedgerUncheckedUpdateManyWithoutOrderInput>
}

export type PaymentLedgerScalarWhereInput = {
  AND?: Prisma.PaymentLedgerScalarWhereInput | Prisma.PaymentLedgerScalarWhereInput[]
  OR?: Prisma.PaymentLedgerScalarWhereInput[]
  NOT?: Prisma.PaymentLedgerScalarWhereInput | Prisma.PaymentLedgerScalarWhereInput[]
  id?: Prisma.StringFilter<"PaymentLedger"> | string
  orderId?: Prisma.StringFilter<"PaymentLedger"> | string
  amount?: Prisma.FloatFilter<"PaymentLedger"> | number
  currency?: Prisma.StringFilter<"PaymentLedger"> | string
  exchangeRate?: Prisma.FloatFilter<"PaymentLedger"> | number
  paymentType?: Prisma.EnumPaymentTypeFilter<"PaymentLedger"> | $Enums.PaymentType
  paymentDate?: Prisma.DateTimeFilter<"PaymentLedger"> | Date | string
  referenceId?: Prisma.StringNullableFilter<"PaymentLedger"> | string | null
  eBrcNumber?: Prisma.StringNullableFilter<"PaymentLedger"> | string | null
  eBrcDate?: Prisma.DateTimeNullableFilter<"PaymentLedger"> | Date | string | null
  bankFircNumber?: Prisma.StringNullableFilter<"PaymentLedger"> | string | null
}

export type PaymentLedgerCreateManyOrderInput = {
  id?: string
  amount: number
  currency: string
  exchangeRate: number
  paymentType: $Enums.PaymentType
  paymentDate: Date | string
  referenceId?: string | null
  eBrcNumber?: string | null
  eBrcDate?: Date | string | null
  bankFircNumber?: string | null
}

export type PaymentLedgerUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  exchangeRate?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentType?: Prisma.EnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bankFircNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PaymentLedgerUncheckedUpdateWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  exchangeRate?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentType?: Prisma.EnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bankFircNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}

export type PaymentLedgerUncheckedUpdateManyWithoutOrderInput = {
  id?: Prisma.StringFieldUpdateOperationsInput | string
  amount?: Prisma.FloatFieldUpdateOperationsInput | number
  currency?: Prisma.StringFieldUpdateOperationsInput | string
  exchangeRate?: Prisma.FloatFieldUpdateOperationsInput | number
  paymentType?: Prisma.EnumPaymentTypeFieldUpdateOperationsInput | $Enums.PaymentType
  paymentDate?: Prisma.DateTimeFieldUpdateOperationsInput | Date | string
  referenceId?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
  eBrcDate?: Prisma.NullableDateTimeFieldUpdateOperationsInput | Date | string | null
  bankFircNumber?: Prisma.NullableStringFieldUpdateOperationsInput | string | null
}



export type PaymentLedgerSelect<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  amount?: boolean
  currency?: boolean
  exchangeRate?: boolean
  paymentType?: boolean
  paymentDate?: boolean
  referenceId?: boolean
  eBrcNumber?: boolean
  eBrcDate?: boolean
  bankFircNumber?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paymentLedger"]>

export type PaymentLedgerSelectCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  amount?: boolean
  currency?: boolean
  exchangeRate?: boolean
  paymentType?: boolean
  paymentDate?: boolean
  referenceId?: boolean
  eBrcNumber?: boolean
  eBrcDate?: boolean
  bankFircNumber?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paymentLedger"]>

export type PaymentLedgerSelectUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetSelect<{
  id?: boolean
  orderId?: boolean
  amount?: boolean
  currency?: boolean
  exchangeRate?: boolean
  paymentType?: boolean
  paymentDate?: boolean
  referenceId?: boolean
  eBrcNumber?: boolean
  eBrcDate?: boolean
  bankFircNumber?: boolean
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}, ExtArgs["result"]["paymentLedger"]>

export type PaymentLedgerSelectScalar = {
  id?: boolean
  orderId?: boolean
  amount?: boolean
  currency?: boolean
  exchangeRate?: boolean
  paymentType?: boolean
  paymentDate?: boolean
  referenceId?: boolean
  eBrcNumber?: boolean
  eBrcDate?: boolean
  bankFircNumber?: boolean
}

export type PaymentLedgerOmit<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = runtime.Types.Extensions.GetOmit<"id" | "orderId" | "amount" | "currency" | "exchangeRate" | "paymentType" | "paymentDate" | "referenceId" | "eBrcNumber" | "eBrcDate" | "bankFircNumber", ExtArgs["result"]["paymentLedger"]>
export type PaymentLedgerInclude<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}
export type PaymentLedgerIncludeCreateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}
export type PaymentLedgerIncludeUpdateManyAndReturn<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  order?: boolean | Prisma.OrderDefaultArgs<ExtArgs>
}

export type $PaymentLedgerPayload<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  name: "PaymentLedger"
  objects: {
    order: Prisma.$OrderPayload<ExtArgs>
  }
  scalars: runtime.Types.Extensions.GetPayloadResult<{
    id: string
    orderId: string
    amount: number
    currency: string
    exchangeRate: number
    paymentType: $Enums.PaymentType
    paymentDate: Date
    referenceId: string | null
    eBrcNumber: string | null
    eBrcDate: Date | null
    bankFircNumber: string | null
  }, ExtArgs["result"]["paymentLedger"]>
  composites: {}
}

export type PaymentLedgerGetPayload<S extends boolean | null | undefined | PaymentLedgerDefaultArgs> = runtime.Types.Result.GetResult<Prisma.$PaymentLedgerPayload, S>

export type PaymentLedgerCountArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> =
  Omit<PaymentLedgerFindManyArgs, 'select' | 'include' | 'distinct' | 'omit'> & {
    select?: PaymentLedgerCountAggregateInputType | true
  }

export interface PaymentLedgerDelegate<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> {
  [K: symbol]: { types: Prisma.TypeMap<ExtArgs>['model']['PaymentLedger'], meta: { name: 'PaymentLedger' } }
  /**
   * Find zero or one PaymentLedger that matches the filter.
   * @param {PaymentLedgerFindUniqueArgs} args - Arguments to find a PaymentLedger
   * @example
   * // Get one PaymentLedger
   * const paymentLedger = await prisma.paymentLedger.findUnique({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUnique<T extends PaymentLedgerFindUniqueArgs>(args: Prisma.SelectSubset<T, PaymentLedgerFindUniqueArgs<ExtArgs>>): Prisma.Prisma__PaymentLedgerClient<runtime.Types.Result.GetResult<Prisma.$PaymentLedgerPayload<ExtArgs>, T, "findUnique", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find one PaymentLedger that matches the filter or throw an error with `error.code='P2025'`
   * if no matches were found.
   * @param {PaymentLedgerFindUniqueOrThrowArgs} args - Arguments to find a PaymentLedger
   * @example
   * // Get one PaymentLedger
   * const paymentLedger = await prisma.paymentLedger.findUniqueOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findUniqueOrThrow<T extends PaymentLedgerFindUniqueOrThrowArgs>(args: Prisma.SelectSubset<T, PaymentLedgerFindUniqueOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaymentLedgerClient<runtime.Types.Result.GetResult<Prisma.$PaymentLedgerPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PaymentLedger that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLedgerFindFirstArgs} args - Arguments to find a PaymentLedger
   * @example
   * // Get one PaymentLedger
   * const paymentLedger = await prisma.paymentLedger.findFirst({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirst<T extends PaymentLedgerFindFirstArgs>(args?: Prisma.SelectSubset<T, PaymentLedgerFindFirstArgs<ExtArgs>>): Prisma.Prisma__PaymentLedgerClient<runtime.Types.Result.GetResult<Prisma.$PaymentLedgerPayload<ExtArgs>, T, "findFirst", GlobalOmitOptions> | null, null, ExtArgs, GlobalOmitOptions>

  /**
   * Find the first PaymentLedger that matches the filter or
   * throw `PrismaKnownClientError` with `P2025` code if no matches were found.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLedgerFindFirstOrThrowArgs} args - Arguments to find a PaymentLedger
   * @example
   * // Get one PaymentLedger
   * const paymentLedger = await prisma.paymentLedger.findFirstOrThrow({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   */
  findFirstOrThrow<T extends PaymentLedgerFindFirstOrThrowArgs>(args?: Prisma.SelectSubset<T, PaymentLedgerFindFirstOrThrowArgs<ExtArgs>>): Prisma.Prisma__PaymentLedgerClient<runtime.Types.Result.GetResult<Prisma.$PaymentLedgerPayload<ExtArgs>, T, "findFirstOrThrow", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Find zero or more PaymentLedgers that matches the filter.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLedgerFindManyArgs} args - Arguments to filter and select certain fields only.
   * @example
   * // Get all PaymentLedgers
   * const paymentLedgers = await prisma.paymentLedger.findMany()
   * 
   * // Get first 10 PaymentLedgers
   * const paymentLedgers = await prisma.paymentLedger.findMany({ take: 10 })
   * 
   * // Only select the `id`
   * const paymentLedgerWithIdOnly = await prisma.paymentLedger.findMany({ select: { id: true } })
   * 
   */
  findMany<T extends PaymentLedgerFindManyArgs>(args?: Prisma.SelectSubset<T, PaymentLedgerFindManyArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaymentLedgerPayload<ExtArgs>, T, "findMany", GlobalOmitOptions>>

  /**
   * Create a PaymentLedger.
   * @param {PaymentLedgerCreateArgs} args - Arguments to create a PaymentLedger.
   * @example
   * // Create one PaymentLedger
   * const PaymentLedger = await prisma.paymentLedger.create({
   *   data: {
   *     // ... data to create a PaymentLedger
   *   }
   * })
   * 
   */
  create<T extends PaymentLedgerCreateArgs>(args: Prisma.SelectSubset<T, PaymentLedgerCreateArgs<ExtArgs>>): Prisma.Prisma__PaymentLedgerClient<runtime.Types.Result.GetResult<Prisma.$PaymentLedgerPayload<ExtArgs>, T, "create", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Create many PaymentLedgers.
   * @param {PaymentLedgerCreateManyArgs} args - Arguments to create many PaymentLedgers.
   * @example
   * // Create many PaymentLedgers
   * const paymentLedger = await prisma.paymentLedger.createMany({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   *     
   */
  createMany<T extends PaymentLedgerCreateManyArgs>(args?: Prisma.SelectSubset<T, PaymentLedgerCreateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Create many PaymentLedgers and returns the data saved in the database.
   * @param {PaymentLedgerCreateManyAndReturnArgs} args - Arguments to create many PaymentLedgers.
   * @example
   * // Create many PaymentLedgers
   * const paymentLedger = await prisma.paymentLedger.createManyAndReturn({
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Create many PaymentLedgers and only return the `id`
   * const paymentLedgerWithIdOnly = await prisma.paymentLedger.createManyAndReturn({
   *   select: { id: true },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  createManyAndReturn<T extends PaymentLedgerCreateManyAndReturnArgs>(args?: Prisma.SelectSubset<T, PaymentLedgerCreateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaymentLedgerPayload<ExtArgs>, T, "createManyAndReturn", GlobalOmitOptions>>

  /**
   * Delete a PaymentLedger.
   * @param {PaymentLedgerDeleteArgs} args - Arguments to delete one PaymentLedger.
   * @example
   * // Delete one PaymentLedger
   * const PaymentLedger = await prisma.paymentLedger.delete({
   *   where: {
   *     // ... filter to delete one PaymentLedger
   *   }
   * })
   * 
   */
  delete<T extends PaymentLedgerDeleteArgs>(args: Prisma.SelectSubset<T, PaymentLedgerDeleteArgs<ExtArgs>>): Prisma.Prisma__PaymentLedgerClient<runtime.Types.Result.GetResult<Prisma.$PaymentLedgerPayload<ExtArgs>, T, "delete", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Update one PaymentLedger.
   * @param {PaymentLedgerUpdateArgs} args - Arguments to update one PaymentLedger.
   * @example
   * // Update one PaymentLedger
   * const paymentLedger = await prisma.paymentLedger.update({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  update<T extends PaymentLedgerUpdateArgs>(args: Prisma.SelectSubset<T, PaymentLedgerUpdateArgs<ExtArgs>>): Prisma.Prisma__PaymentLedgerClient<runtime.Types.Result.GetResult<Prisma.$PaymentLedgerPayload<ExtArgs>, T, "update", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>

  /**
   * Delete zero or more PaymentLedgers.
   * @param {PaymentLedgerDeleteManyArgs} args - Arguments to filter PaymentLedgers to delete.
   * @example
   * // Delete a few PaymentLedgers
   * const { count } = await prisma.paymentLedger.deleteMany({
   *   where: {
   *     // ... provide filter here
   *   }
   * })
   * 
   */
  deleteMany<T extends PaymentLedgerDeleteManyArgs>(args?: Prisma.SelectSubset<T, PaymentLedgerDeleteManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PaymentLedgers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLedgerUpdateManyArgs} args - Arguments to update one or more rows.
   * @example
   * // Update many PaymentLedgers
   * const paymentLedger = await prisma.paymentLedger.updateMany({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: {
   *     // ... provide data here
   *   }
   * })
   * 
   */
  updateMany<T extends PaymentLedgerUpdateManyArgs>(args: Prisma.SelectSubset<T, PaymentLedgerUpdateManyArgs<ExtArgs>>): Prisma.PrismaPromise<Prisma.BatchPayload>

  /**
   * Update zero or more PaymentLedgers and returns the data updated in the database.
   * @param {PaymentLedgerUpdateManyAndReturnArgs} args - Arguments to update many PaymentLedgers.
   * @example
   * // Update many PaymentLedgers
   * const paymentLedger = await prisma.paymentLedger.updateManyAndReturn({
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * 
   * // Update zero or more PaymentLedgers and only return the `id`
   * const paymentLedgerWithIdOnly = await prisma.paymentLedger.updateManyAndReturn({
   *   select: { id: true },
   *   where: {
   *     // ... provide filter here
   *   },
   *   data: [
   *     // ... provide data here
   *   ]
   * })
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * 
   */
  updateManyAndReturn<T extends PaymentLedgerUpdateManyAndReturnArgs>(args: Prisma.SelectSubset<T, PaymentLedgerUpdateManyAndReturnArgs<ExtArgs>>): Prisma.PrismaPromise<runtime.Types.Result.GetResult<Prisma.$PaymentLedgerPayload<ExtArgs>, T, "updateManyAndReturn", GlobalOmitOptions>>

  /**
   * Create or update one PaymentLedger.
   * @param {PaymentLedgerUpsertArgs} args - Arguments to update or create a PaymentLedger.
   * @example
   * // Update or create a PaymentLedger
   * const paymentLedger = await prisma.paymentLedger.upsert({
   *   create: {
   *     // ... data to create a PaymentLedger
   *   },
   *   update: {
   *     // ... in case it already exists, update
   *   },
   *   where: {
   *     // ... the filter for the PaymentLedger we want to update
   *   }
   * })
   */
  upsert<T extends PaymentLedgerUpsertArgs>(args: Prisma.SelectSubset<T, PaymentLedgerUpsertArgs<ExtArgs>>): Prisma.Prisma__PaymentLedgerClient<runtime.Types.Result.GetResult<Prisma.$PaymentLedgerPayload<ExtArgs>, T, "upsert", GlobalOmitOptions>, never, ExtArgs, GlobalOmitOptions>


  /**
   * Count the number of PaymentLedgers.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLedgerCountArgs} args - Arguments to filter PaymentLedgers to count.
   * @example
   * // Count the number of PaymentLedgers
   * const count = await prisma.paymentLedger.count({
   *   where: {
   *     // ... the filter for the PaymentLedgers we want to count
   *   }
   * })
  **/
  count<T extends PaymentLedgerCountArgs>(
    args?: Prisma.Subset<T, PaymentLedgerCountArgs>,
  ): Prisma.PrismaPromise<
    T extends runtime.Types.Utils.Record<'select', any>
      ? T['select'] extends true
        ? number
        : Prisma.GetScalarType<T['select'], PaymentLedgerCountAggregateOutputType>
      : number
  >

  /**
   * Allows you to perform aggregations operations on a PaymentLedger.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLedgerAggregateArgs} args - Select which aggregations you would like to apply and on what fields.
   * @example
   * // Ordered by age ascending
   * // Where email contains prisma.io
   * // Limited to the 10 users
   * const aggregations = await prisma.user.aggregate({
   *   _avg: {
   *     age: true,
   *   },
   *   where: {
   *     email: {
   *       contains: "prisma.io",
   *     },
   *   },
   *   orderBy: {
   *     age: "asc",
   *   },
   *   take: 10,
   * })
  **/
  aggregate<T extends PaymentLedgerAggregateArgs>(args: Prisma.Subset<T, PaymentLedgerAggregateArgs>): Prisma.PrismaPromise<GetPaymentLedgerAggregateType<T>>

  /**
   * Group by PaymentLedger.
   * Note, that providing `undefined` is treated as the value not being there.
   * Read more here: https://pris.ly/d/null-undefined
   * @param {PaymentLedgerGroupByArgs} args - Group by arguments.
   * @example
   * // Group by city, order by createdAt, get count
   * const result = await prisma.user.groupBy({
   *   by: ['city', 'createdAt'],
   *   orderBy: {
   *     createdAt: true
   *   },
   *   _count: {
   *     _all: true
   *   },
   * })
   * 
  **/
  groupBy<
    T extends PaymentLedgerGroupByArgs,
    HasSelectOrTake extends Prisma.Or<
      Prisma.Extends<'skip', Prisma.Keys<T>>,
      Prisma.Extends<'take', Prisma.Keys<T>>
    >,
    OrderByArg extends Prisma.True extends HasSelectOrTake
      ? { orderBy: PaymentLedgerGroupByArgs['orderBy'] }
      : { orderBy?: PaymentLedgerGroupByArgs['orderBy'] },
    OrderFields extends Prisma.ExcludeUnderscoreKeys<Prisma.Keys<Prisma.MaybeTupleToUnion<T['orderBy']>>>,
    ByFields extends Prisma.MaybeTupleToUnion<T['by']>,
    ByValid extends Prisma.Has<ByFields, OrderFields>,
    HavingFields extends Prisma.GetHavingFields<T['having']>,
    HavingValid extends Prisma.Has<ByFields, HavingFields>,
    ByEmpty extends T['by'] extends never[] ? Prisma.True : Prisma.False,
    InputErrors extends ByEmpty extends Prisma.True
    ? `Error: "by" must not be empty.`
    : HavingValid extends Prisma.False
    ? {
        [P in HavingFields]: P extends ByFields
          ? never
          : P extends string
          ? `Error: Field "${P}" used in "having" needs to be provided in "by".`
          : [
              Error,
              'Field ',
              P,
              ` in "having" needs to be provided in "by"`,
            ]
      }[HavingFields]
    : 'take' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "take", you also need to provide "orderBy"'
    : 'skip' extends Prisma.Keys<T>
    ? 'orderBy' extends Prisma.Keys<T>
      ? ByValid extends Prisma.True
        ? {}
        : {
            [P in OrderFields]: P extends ByFields
              ? never
              : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
          }[OrderFields]
      : 'Error: If you provide "skip", you also need to provide "orderBy"'
    : ByValid extends Prisma.True
    ? {}
    : {
        [P in OrderFields]: P extends ByFields
          ? never
          : `Error: Field "${P}" in "orderBy" needs to be provided in "by"`
      }[OrderFields]
  >(args: Prisma.SubsetIntersection<T, PaymentLedgerGroupByArgs, OrderByArg> & InputErrors): {} extends InputErrors ? GetPaymentLedgerGroupByPayload<T> : Prisma.PrismaPromise<InputErrors>
/**
 * Fields of the PaymentLedger model
 */
readonly fields: PaymentLedgerFieldRefs;
}

/**
 * The delegate class that acts as a "Promise-like" for PaymentLedger.
 * Why is this prefixed with `Prisma__`?
 * Because we want to prevent naming conflicts as mentioned in
 * https://github.com/prisma/prisma-client-js/issues/707
 */
export interface Prisma__PaymentLedgerClient<T, Null = never, ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs, GlobalOmitOptions = {}> extends Prisma.PrismaPromise<T> {
  readonly [Symbol.toStringTag]: "PrismaPromise"
  order<T extends Prisma.OrderDefaultArgs<ExtArgs> = {}>(args?: Prisma.Subset<T, Prisma.OrderDefaultArgs<ExtArgs>>): Prisma.Prisma__OrderClient<runtime.Types.Result.GetResult<Prisma.$OrderPayload<ExtArgs>, T, "findUniqueOrThrow", GlobalOmitOptions> | Null, Null, ExtArgs, GlobalOmitOptions>
  /**
   * Attaches callbacks for the resolution and/or rejection of the Promise.
   * @param onfulfilled The callback to execute when the Promise is resolved.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of which ever callback is executed.
   */
  then<TResult1 = T, TResult2 = never>(onfulfilled?: ((value: T) => TResult1 | PromiseLike<TResult1>) | undefined | null, onrejected?: ((reason: any) => TResult2 | PromiseLike<TResult2>) | undefined | null): runtime.Types.Utils.JsPromise<TResult1 | TResult2>
  /**
   * Attaches a callback for only the rejection of the Promise.
   * @param onrejected The callback to execute when the Promise is rejected.
   * @returns A Promise for the completion of the callback.
   */
  catch<TResult = never>(onrejected?: ((reason: any) => TResult | PromiseLike<TResult>) | undefined | null): runtime.Types.Utils.JsPromise<T | TResult>
  /**
   * Attaches a callback that is invoked when the Promise is settled (fulfilled or rejected). The
   * resolved value cannot be modified from the callback.
   * @param onfinally The callback to execute when the Promise is settled (fulfilled or rejected).
   * @returns A Promise for the completion of the callback.
   */
  finally(onfinally?: (() => void) | undefined | null): runtime.Types.Utils.JsPromise<T>
}




/**
 * Fields of the PaymentLedger model
 */
export interface PaymentLedgerFieldRefs {
  readonly id: Prisma.FieldRef<"PaymentLedger", 'String'>
  readonly orderId: Prisma.FieldRef<"PaymentLedger", 'String'>
  readonly amount: Prisma.FieldRef<"PaymentLedger", 'Float'>
  readonly currency: Prisma.FieldRef<"PaymentLedger", 'String'>
  readonly exchangeRate: Prisma.FieldRef<"PaymentLedger", 'Float'>
  readonly paymentType: Prisma.FieldRef<"PaymentLedger", 'PaymentType'>
  readonly paymentDate: Prisma.FieldRef<"PaymentLedger", 'DateTime'>
  readonly referenceId: Prisma.FieldRef<"PaymentLedger", 'String'>
  readonly eBrcNumber: Prisma.FieldRef<"PaymentLedger", 'String'>
  readonly eBrcDate: Prisma.FieldRef<"PaymentLedger", 'DateTime'>
  readonly bankFircNumber: Prisma.FieldRef<"PaymentLedger", 'String'>
}
    

// Custom InputTypes
/**
 * PaymentLedger findUnique
 */
export type PaymentLedgerFindUniqueArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLedger
   */
  select?: Prisma.PaymentLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLedger
   */
  omit?: Prisma.PaymentLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLedgerInclude<ExtArgs> | null
  /**
   * Filter, which PaymentLedger to fetch.
   */
  where: Prisma.PaymentLedgerWhereUniqueInput
}

/**
 * PaymentLedger findUniqueOrThrow
 */
export type PaymentLedgerFindUniqueOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLedger
   */
  select?: Prisma.PaymentLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLedger
   */
  omit?: Prisma.PaymentLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLedgerInclude<ExtArgs> | null
  /**
   * Filter, which PaymentLedger to fetch.
   */
  where: Prisma.PaymentLedgerWhereUniqueInput
}

/**
 * PaymentLedger findFirst
 */
export type PaymentLedgerFindFirstArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLedger
   */
  select?: Prisma.PaymentLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLedger
   */
  omit?: Prisma.PaymentLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLedgerInclude<ExtArgs> | null
  /**
   * Filter, which PaymentLedger to fetch.
   */
  where?: Prisma.PaymentLedgerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaymentLedgers to fetch.
   */
  orderBy?: Prisma.PaymentLedgerOrderByWithRelationInput | Prisma.PaymentLedgerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PaymentLedgers.
   */
  cursor?: Prisma.PaymentLedgerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaymentLedgers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaymentLedgers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PaymentLedgers.
   */
  distinct?: Prisma.PaymentLedgerScalarFieldEnum | Prisma.PaymentLedgerScalarFieldEnum[]
}

/**
 * PaymentLedger findFirstOrThrow
 */
export type PaymentLedgerFindFirstOrThrowArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLedger
   */
  select?: Prisma.PaymentLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLedger
   */
  omit?: Prisma.PaymentLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLedgerInclude<ExtArgs> | null
  /**
   * Filter, which PaymentLedger to fetch.
   */
  where?: Prisma.PaymentLedgerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaymentLedgers to fetch.
   */
  orderBy?: Prisma.PaymentLedgerOrderByWithRelationInput | Prisma.PaymentLedgerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for searching for PaymentLedgers.
   */
  cursor?: Prisma.PaymentLedgerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaymentLedgers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaymentLedgers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PaymentLedgers.
   */
  distinct?: Prisma.PaymentLedgerScalarFieldEnum | Prisma.PaymentLedgerScalarFieldEnum[]
}

/**
 * PaymentLedger findMany
 */
export type PaymentLedgerFindManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLedger
   */
  select?: Prisma.PaymentLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLedger
   */
  omit?: Prisma.PaymentLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLedgerInclude<ExtArgs> | null
  /**
   * Filter, which PaymentLedgers to fetch.
   */
  where?: Prisma.PaymentLedgerWhereInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/sorting Sorting Docs}
   * 
   * Determine the order of PaymentLedgers to fetch.
   */
  orderBy?: Prisma.PaymentLedgerOrderByWithRelationInput | Prisma.PaymentLedgerOrderByWithRelationInput[]
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination#cursor-based-pagination Cursor Docs}
   * 
   * Sets the position for listing PaymentLedgers.
   */
  cursor?: Prisma.PaymentLedgerWhereUniqueInput
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Take `±n` PaymentLedgers from the position of the cursor.
   */
  take?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/pagination Pagination Docs}
   * 
   * Skip the first `n` PaymentLedgers.
   */
  skip?: number
  /**
   * {@link https://www.prisma.io/docs/concepts/components/prisma-client/distinct Distinct Docs}
   * 
   * Filter by unique combinations of PaymentLedgers.
   */
  distinct?: Prisma.PaymentLedgerScalarFieldEnum | Prisma.PaymentLedgerScalarFieldEnum[]
}

/**
 * PaymentLedger create
 */
export type PaymentLedgerCreateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLedger
   */
  select?: Prisma.PaymentLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLedger
   */
  omit?: Prisma.PaymentLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLedgerInclude<ExtArgs> | null
  /**
   * The data needed to create a PaymentLedger.
   */
  data: Prisma.XOR<Prisma.PaymentLedgerCreateInput, Prisma.PaymentLedgerUncheckedCreateInput>
}

/**
 * PaymentLedger createMany
 */
export type PaymentLedgerCreateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to create many PaymentLedgers.
   */
  data: Prisma.PaymentLedgerCreateManyInput | Prisma.PaymentLedgerCreateManyInput[]
  skipDuplicates?: boolean
}

/**
 * PaymentLedger createManyAndReturn
 */
export type PaymentLedgerCreateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLedger
   */
  select?: Prisma.PaymentLedgerSelectCreateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLedger
   */
  omit?: Prisma.PaymentLedgerOmit<ExtArgs> | null
  /**
   * The data used to create many PaymentLedgers.
   */
  data: Prisma.PaymentLedgerCreateManyInput | Prisma.PaymentLedgerCreateManyInput[]
  skipDuplicates?: boolean
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLedgerIncludeCreateManyAndReturn<ExtArgs> | null
}

/**
 * PaymentLedger update
 */
export type PaymentLedgerUpdateArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLedger
   */
  select?: Prisma.PaymentLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLedger
   */
  omit?: Prisma.PaymentLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLedgerInclude<ExtArgs> | null
  /**
   * The data needed to update a PaymentLedger.
   */
  data: Prisma.XOR<Prisma.PaymentLedgerUpdateInput, Prisma.PaymentLedgerUncheckedUpdateInput>
  /**
   * Choose, which PaymentLedger to update.
   */
  where: Prisma.PaymentLedgerWhereUniqueInput
}

/**
 * PaymentLedger updateMany
 */
export type PaymentLedgerUpdateManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * The data used to update PaymentLedgers.
   */
  data: Prisma.XOR<Prisma.PaymentLedgerUpdateManyMutationInput, Prisma.PaymentLedgerUncheckedUpdateManyInput>
  /**
   * Filter which PaymentLedgers to update
   */
  where?: Prisma.PaymentLedgerWhereInput
  /**
   * Limit how many PaymentLedgers to update.
   */
  limit?: number
}

/**
 * PaymentLedger updateManyAndReturn
 */
export type PaymentLedgerUpdateManyAndReturnArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLedger
   */
  select?: Prisma.PaymentLedgerSelectUpdateManyAndReturn<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLedger
   */
  omit?: Prisma.PaymentLedgerOmit<ExtArgs> | null
  /**
   * The data used to update PaymentLedgers.
   */
  data: Prisma.XOR<Prisma.PaymentLedgerUpdateManyMutationInput, Prisma.PaymentLedgerUncheckedUpdateManyInput>
  /**
   * Filter which PaymentLedgers to update
   */
  where?: Prisma.PaymentLedgerWhereInput
  /**
   * Limit how many PaymentLedgers to update.
   */
  limit?: number
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLedgerIncludeUpdateManyAndReturn<ExtArgs> | null
}

/**
 * PaymentLedger upsert
 */
export type PaymentLedgerUpsertArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLedger
   */
  select?: Prisma.PaymentLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLedger
   */
  omit?: Prisma.PaymentLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLedgerInclude<ExtArgs> | null
  /**
   * The filter to search for the PaymentLedger to update in case it exists.
   */
  where: Prisma.PaymentLedgerWhereUniqueInput
  /**
   * In case the PaymentLedger found by the `where` argument doesn't exist, create a new PaymentLedger with this data.
   */
  create: Prisma.XOR<Prisma.PaymentLedgerCreateInput, Prisma.PaymentLedgerUncheckedCreateInput>
  /**
   * In case the PaymentLedger was found with the provided `where` argument, update it with this data.
   */
  update: Prisma.XOR<Prisma.PaymentLedgerUpdateInput, Prisma.PaymentLedgerUncheckedUpdateInput>
}

/**
 * PaymentLedger delete
 */
export type PaymentLedgerDeleteArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLedger
   */
  select?: Prisma.PaymentLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLedger
   */
  omit?: Prisma.PaymentLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLedgerInclude<ExtArgs> | null
  /**
   * Filter which PaymentLedger to delete.
   */
  where: Prisma.PaymentLedgerWhereUniqueInput
}

/**
 * PaymentLedger deleteMany
 */
export type PaymentLedgerDeleteManyArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Filter which PaymentLedgers to delete
   */
  where?: Prisma.PaymentLedgerWhereInput
  /**
   * Limit how many PaymentLedgers to delete.
   */
  limit?: number
}

/**
 * PaymentLedger without action
 */
export type PaymentLedgerDefaultArgs<ExtArgs extends runtime.Types.Extensions.InternalArgs = runtime.Types.Extensions.DefaultArgs> = {
  /**
   * Select specific fields to fetch from the PaymentLedger
   */
  select?: Prisma.PaymentLedgerSelect<ExtArgs> | null
  /**
   * Omit specific fields from the PaymentLedger
   */
  omit?: Prisma.PaymentLedgerOmit<ExtArgs> | null
  /**
   * Choose, which related nodes to fetch as well
   */
  include?: Prisma.PaymentLedgerInclude<ExtArgs> | null
}
